### ISSUE TITLE
Python 2.7 Support?

### ISSUE THREAD

**Issue by nikhilmitrax** [viniciuschiele/flask-apidoc#1]
Hi!

Quick question : Why isn't Python 2.7 supported?

**Comment by viniciuschiele** [comment]
Just because I don't work with Python 2.7, I didn't even test it against Python 2.7 to see what would happen.

This week I will do it and I will let you know.

Cheers

**Comment by nikhilmitrax** [comment]
I made a fork of this and tried it out by modifying things a bit, if you want, I can work it out.

**Comment by viniciuschiele** [comment]
Sure, create a pull request with your changes.

Let me know If you have any other suggestion to improve this library.

Thanks!

**Comment by viniciuschiele** [comment]
I just released a new version with support to Python 2.7

I made a little change in code, I removed the dependency to functools32 and I implemented my own cache decorator.

Thanks for the contribution #2
