### ISSUE TITLE
flask-apidoc two bug

### ISSUE THREAD

**Issue by 512868516** [viniciuschiele/flask-apidoc#11]
1. @api can not identify <string:sg_id> 
   @api {DELETE} /api/v1/sgs/<string:sg_id> delete firewall
2. url with GET and POST views, only identify one view.
    @api {GET} /api/v1/sgs/ retuen all sgs
    @api {POST} /api/v1/sgs create sgs

**Comment by 512868516** [comment]
@viniciuschiele @nikhilmitrax @colelloa

**Comment by viniciuschiele** [comment]
Hi,

That is a ApiDoc's limitation, you need to create a ticket on their [github](https://github.com/apidoc/apidoc).
