### ISSUE TITLE
when parse error no showing of info

### ISSUE THREAD

**Issue by tmacjx** [viniciuschiele/flask-apidoc#12]
when apidoc have some parse error. Cmd execute 'python manage.py apidoc' show nothing, only show process exit with code 1. No any valueable  info explain what happend.When I execute cmd with apidoc like 'apidoc -i srv/ -o static/docs', it worked show valueable info.

**Comment by tmacjx** [comment]
![image](https://user-images.githubusercontent.com/11555807/47009763-e21e1f00-d16f-11e8-8ee4-73274e3b669d.png)

**Comment by tmacjx** [comment]
![image](https://user-images.githubusercontent.com/11555807/47009890-24dff700-d170-11e8-89c3-9e1ae6e4b81f.png)

**Comment by viniciuschiele** [comment]
Hi @tmacjx 

Thanks for reporting it, I will work on it and let you know soon

**Comment by viniciuschiele** [comment]
I've released a new version 1.2.0 that adds the output from ApiDoc.

Feel free to open this issue again if it doesn't work as expected.
