### ISSUE TITLE
error in __send_api_file, structure of api_project.json changed

### ISSUE THREAD

**Issue by pdoronila** [viniciuschiele/flask-apidoc#4]
[Original Code on Line 96](https://github.com/viniciuschiele/flask-apidoc/blob/master/flask_apidoc/apidoc.py#L95) assumes api_project.json  file generated by apidocs has a attribute "url" but that  url attribute is now under the "generator" attribute. Pull request for fix incoming....

**Comment by viniciuschiele** [comment]
Hi @pdoronila 

I'm using ApiDoc 0.16.1 (latest version) and the attribute **url** is still in the root level

```
{
  "name": "Flask REST API",
  "version": "1.0.0",
  "description": "A Flask REST API example",
  "title": "A Flask REST API example",
  "url": "http://localhost:5000",
  "sampleUrl": false,
  "apidoc": "0.2.0",
  "generator": {
    "name": "apidoc",
    "time": "2016-11-11T21:31:18.885Z",
    "url": "http://apidocjs.com",
    "version": "0.16.1"
  }
}
```

I've been using it and I've not seen any issue.

Cheers!
