### ISSUE TITLE
Help, It does not work

### ISSUE THREAD

**Issue by nslogx** [viniciuschiele/flask-apidoc#9]
![image](https://user-images.githubusercontent.com/8692455/34933522-1beeacbc-fa12-11e7-9310-f344f6973e40.png)
![image](https://user-images.githubusercontent.com/8692455/34933254-1108e57a-fa11-11e7-987d-c1c0ef0e26e7.png)
![image](https://user-images.githubusercontent.com/8692455/34933444-c8e670ae-fa11-11e7-8e4e-f9339288f7a6.png)
![image](https://user-images.githubusercontent.com/8692455/34933457-d48f8e5e-fa11-11e7-9e10-07aef689c058.png)

my project is use Blueprint and flask-restful,but python manage.py apidoc does not work for me, thanks

**Comment by nslogx** [comment]
@viniciuschiele please help me,thanks

**Comment by viniciuschiele** [comment]
Hi,

Do you get an error message?

**Comment by nslogx** [comment]
@viniciuschiele none
but i user apidoc -i  xx -o xx instead, it works,thanks
